name: FactionsPro
author: Tethered_, edited by VMPE Development Team
description: A Extended Factions plugin. [new-methods Branch]
version: 2.1.1-BETA
main: FactionsPro\FactionMain
api: [3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 4.0.0]
softdepend: ["PureChat", "AntiSpamPro", "EssentialsPE", "EconomyAPI"]
commands:
  f:
    description: Faction commands.
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
