name: FactionsPro
author: Tethered_, edited by VMPE Development Team
description: A Extended Factions plugin. [new-methods Branch]
version: 2.1.0-NEW
main: FactionsPro\FactionMain
api: [3.0.0, 3.0.1]
softdepend: ["PureChat", "AntiSpamPro", "EssentialsPE", "EconomyAPI"]
commands:
  f:
    description: Faction commands.
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
