---
name: FactionsPro
author: Tethered_
description: Lets Bring Back FactionsPro The Better Way!
version: 2.5.0-BETA
main: FactionsPro\FactionMain
api:
- 3.0.0-ALPHA11
commands:
  f:
    permission: f.command
permissions:
  f.command:
    default: true
...
